//Try catch block

try {
  console.log(fluit1 + fluit2);
} catch (error) {
  console.log(err);
  console.log("There was an error");
  console.log("The error was saved in the error log");
}
console.log("My program does not stop");
